### ISSUE TITLE
Explaination on how to setup

### ISSUE THREAD

**Issue by MacaronFR** [alexivkin/SARDELKA#1]
Hello
Recently i found your tool to auto backup on remote server
I follow your step to setup but on the 7th step of setup backupstorage I'm not sure how to fill backup.schedule to make it work properly
Also did this tool allow me to backup from different source (and pull on every source the modification from the backup server)

Thanks

**Comment by alexivkin** [comment]
@MacaronFR take a look at the [backup.schedule.sample](https://github.com/alexivkin/SARDELKA/blob/master/backup.schedule.sample) for the details on how to set it up. The tool does allow backing up a different source.
